import graphviz
import os
g=graphviz.Digraph(format="svg", comment="projects")
g.node("concur_chan")
g.node("gogrpc")
g.node("fayne")
g.node("gogui")
g.node("tensorflow")
g.node("encrypt")
g.node("compress")
g.node("key_secure")
g.node("gps")
g.node("grpc")
g.node("renderscript")
g.node("camera")
g.node("sensors")
g.node("kot_opengles")
g.node("electron")
g.node("dask")
g.node("cupy")
g.node("pycuda")
g.node("numba")
g.node("pytorch")
g.node("nlp")
g.node("fastai2")
g.node("fastai")
g.node("megatron")
g.node("waveguide")
g.node("webengine")
g.node("trellis")
g.node("visdom")
g.node("tkinter")
g.node("glumpy")
g.node("webkit")
g.node("pyqt")
g.node("gtk3")
g.node("pywx")
g.node("pygui")
g.node("selenium")
g.node("helium")
g.node("autoweb")
g.node("pyvulkan")
g.node("ai")
g.node("phx")
g.node("termimg")
g.node("python_in_cpp")
g.node("pybind11")
g.node("asio")
g.node("wx")
g.node("imgui")
g.node("fltk")
g.node("qt")
g.node("gtk")
g.node("gui")
g.node("stm32")
g.node("psoc")
g.node("embed")
g.node("tbb")
g.node("lua_in_cpp")
g.node("script")
g.node("vulkan")
g.node("wasm")
g.node("android")
g.node("optix")
g.node("uprof")
g.node("cuda")
g.node("finance")
g.node("swift", color="blue", URL="https://github.com/plops/cl-swift-generator")
g.node("matlab", color="blue", URL="https://github.com/plops/cl-m-generator")
g.node("js", color="blue", URL="https://github.com/plops/cl-js-generator")
g.node("go", color="blue", URL="https://github.com/plops/cl-golang-generator")
g.node("elixir", color="blue", URL="https://github.com/plops/cl-elixir-generator")
g.node("rust", color="blue", URL="https://github.com/plops/cl-rust-generator")
g.node("kotlin", color="blue", URL="https://github.com/plops/cl-kotlin-generator")
g.node("python", color="blue", URL="https://github.com/plops/cl-python-generator")
g.node("cpp2", color="blue", URL="https://github.com/plops/cl-cpp-generator2")
g.node("sar")
g.node("pluto")
g.node("sdr")
g.node("sexpr")
g.node("main")
g.edge("main", "sexpr")
g.edge("main", "sdr")
g.edge("sdr", "pluto")
g.edge("sdr", "sar")
g.edge("sexpr", "cpp2")
g.edge("sexpr", "python")
g.edge("sexpr", "kotlin")
g.edge("sexpr", "rust")
g.edge("sexpr", "elixir")
g.edge("sexpr", "go")
g.edge("sexpr", "js")
g.edge("sexpr", "matlab")
g.edge("sexpr", "swift")
g.edge("python", "finance")
g.edge("rust", "cuda")
g.edge("rust", "pluto")
g.edge("rust", "uprof")
g.edge("cpp2", "optix")
g.edge("main", "android")
g.edge("cpp2", "wasm")
g.edge("cpp2", "cuda")
g.edge("cpp2", "vulkan")
g.edge("cpp2", "script")
g.edge("script", "lua_in_cpp")
g.edge("cpp2", "tbb")
g.edge("cpp2", "embed")
g.edge("embed", "pluto")
g.edge("embed", "psoc")
g.edge("embed", "stm32")
g.edge("cpp2", "sar")
g.edge("cpp2", "gui")
g.edge("gui", "gtk")
g.edge("gui", "qt")
g.edge("gui", "fltk")
g.edge("gui", "imgui")
g.edge("gui", "wx")
g.edge("cpp2", "asio")
g.edge("cpp2", "script")
g.edge("script", "pybind11")
g.edge("pybind11", "python_in_cpp")
g.edge("cpp2", "termimg")
g.edge("elixir", "phx")
g.edge("python", "ai")
g.edge("python", "pyvulkan")
g.edge("python", "autoweb")
g.edge("autoweb", "helium")
g.edge("autoweb", "selenium")
g.edge("python", "pygui")
g.edge("pygui", "pywx")
g.edge("pygui", "gtk3")
g.edge("pygui", "pyqt")
g.edge("pyqt", "webkit")
g.edge("pygui", "glumpy")
g.edge("pygui", "tkinter")
g.edge("pygui", "visdom")
g.edge("qt", "trellis")
g.edge("qt", "webengine")
g.edge("python", "waveguide")
g.edge("ai", "megatron")
g.edge("ai", "fastai")
g.edge("ai", "fastai2")
g.edge("fastai2", "nlp")
g.edge("ai", "pytorch")
g.edge("python", "numba")
g.edge("python", "pycuda")
g.edge("python", "cupy")
g.edge("python", "dask")
g.edge("js", "electron")
g.edge("kotlin", "kot_opengles")
g.edge("kotlin", "sensors")
g.edge("kotlin", "camera")
g.edge("kotlin", "renderscript")
g.edge("kotlin", "grpc")
g.edge("kotlin", "gps")
g.edge("kotlin", "key_secure")
g.edge("kotlin", "compress")
g.edge("kotlin", "encrypt")
g.edge("swift", "tensorflow")
g.edge("go", "gogui")
g.edge("gogui", "fayne")
g.edge("go", "gogrpc")
g.edge("go", "concur_chan")
g.render()
os.rename("Digraph.gv.svg", "graph.svg")