import graphviz
import os
g0=graphviz.Digraph(format="svg", comment="projects")
g0.node("termimg")
g0.node("python_in_cpp")
g0.node("pybind11")
g0.node("asio")
g0.node("wx")
g0.node("imgui")
g0.node("fltk")
g0.node("qt")
g0.node("gtk")
g0.node("gui")
g0.node("sar")
g0.node("stm32")
g0.node("psoc")
g0.node("pluto")
g0.node("embed")
g0.node("tbb")
g0.node("lua_in_cpp")
g0.node("script")
g0.node("vulkan")
g0.node("cuda")
g0.node("wasm")
g0.node("optix")
g0.node("cpp2")
g0.edge("cpp2", "optix")
g0.edge("cpp2", "wasm")
g0.edge("cpp2", "cuda")
g0.edge("cpp2", "vulkan")
g0.edge("cpp2", "script")
g0.edge("script", "lua_in_cpp")
g0.edge("cpp2", "tbb")
g0.edge("cpp2", "embed")
g0.edge("embed", "pluto")
g0.edge("embed", "psoc")
g0.edge("embed", "stm32")
g0.edge("cpp2", "sar")
g0.edge("cpp2", "gui")
g0.edge("gui", "gtk")
g0.edge("gui", "qt")
g0.edge("gui", "fltk")
g0.edge("gui", "imgui")
g0.edge("gui", "wx")
g0.edge("cpp2", "asio")
g0.edge("cpp2", "script")
g0.edge("script", "pybind11")
g0.edge("pybind11", "python_in_cpp")
g0.edge("cpp2", "termimg")
g0.render()
os.rename("Digraph.gv.svg", "graph0.svg")
g1=graphviz.Digraph(format="svg", comment="projects")
g1.node("dask")
g1.node("cupy")
g1.node("pycuda")
g1.node("numba")
g1.node("pytorch")
g1.node("nlp")
g1.node("fastai2")
g1.node("fastai")
g1.node("megatron")
g1.node("waveguide")
g1.node("webengine")
g1.node("trellis")
g1.node("qt")
g1.node("visdom")
g1.node("tkinter")
g1.node("glumpy")
g1.node("webkit")
g1.node("pyqt")
g1.node("gtk3")
g1.node("pywx")
g1.node("pygui")
g1.node("selenium")
g1.node("helium")
g1.node("autoweb")
g1.node("pyvulkan")
g1.node("ai")
g1.node("python")
g1.edge("python", "ai")
g1.edge("python", "pyvulkan")
g1.edge("python", "autoweb")
g1.edge("autoweb", "helium")
g1.edge("autoweb", "selenium")
g1.edge("python", "pygui")
g1.edge("pygui", "pywx")
g1.edge("pygui", "gtk3")
g1.edge("pygui", "pyqt")
g1.edge("pyqt", "webkit")
g1.edge("pygui", "glumpy")
g1.edge("pygui", "tkinter")
g1.edge("pygui", "visdom")
g1.edge("qt", "trellis")
g1.edge("qt", "webengine")
g1.edge("python", "waveguide")
g1.edge("ai", "megatron")
g1.edge("ai", "fastai")
g1.edge("ai", "fastai2")
g1.edge("fastai2", "nlp")
g1.edge("ai", "pytorch")
g1.edge("python", "numba")
g1.edge("python", "pycuda")
g1.edge("python", "cupy")
g1.edge("python", "dask")
g1.render()
os.rename("Digraph.gv.svg", "graph1.svg")
g2=graphviz.Digraph(format="svg", comment="projects")
g2.node("encrypt")
g2.node("compress")
g2.node("key_secure")
g2.node("gps")
g2.node("grpc")
g2.node("renderscript")
g2.node("camera")
g2.node("sensors")
g2.node("kot_opengles")
g2.node("kotlin")
g2.edge("kotlin", "kot_opengles")
g2.edge("kotlin", "sensors")
g2.edge("kotlin", "camera")
g2.edge("kotlin", "renderscript")
g2.edge("kotlin", "grpc")
g2.edge("kotlin", "gps")
g2.edge("kotlin", "key_secure")
g2.edge("kotlin", "compress")
g2.edge("kotlin", "encrypt")
g2.render()
os.rename("Digraph.gv.svg", "graph2.svg")
g3=graphviz.Digraph(format="svg", comment="projects")
g3.node("concur_chan")
g3.node("gogrpc")
g3.node("fayne")
g3.node("gogui")
g3.node("tensorflow")
g3.node("electron")
g3.node("phx")
g3.node("uprof")
g3.node("cuda")
g3.node("finance")
g3.node("swift", color="blue", URL="https://github.com/plops/cl-swift-generator")
g3.node("matlab", color="blue", URL="https://github.com/plops/cl-m-generator")
g3.node("js", color="blue", URL="https://github.com/plops/cl-js-generator")
g3.node("go", color="blue", URL="https://github.com/plops/cl-golang-generator")
g3.node("elixir", color="blue", URL="https://github.com/plops/cl-elixir-generator")
g3.node("rust", color="blue", URL="https://github.com/plops/cl-rust-generator")
g3.node("kotlin", color="blue", URL="https://github.com/plops/cl-kotlin-generator")
g3.node("python", color="blue", URL="https://github.com/plops/cl-python-generator")
g3.node("cpp2", color="blue", URL="https://github.com/plops/cl-cpp-generator2")
g3.node("sar")
g3.node("pluto")
g3.node("android")
g3.node("sdr")
g3.node("sexpr")
g3.node("main")
g3.edge("main", "sexpr")
g3.edge("main", "sdr")
g3.edge("main", "android")
g3.edge("sdr", "pluto")
g3.edge("sdr", "sar")
g3.edge("sexpr", "cpp2")
g3.edge("sexpr", "python")
g3.edge("sexpr", "kotlin")
g3.edge("sexpr", "rust")
g3.edge("sexpr", "elixir")
g3.edge("sexpr", "go")
g3.edge("sexpr", "js")
g3.edge("sexpr", "matlab")
g3.edge("sexpr", "swift")
g3.edge("python", "finance")
g3.edge("rust", "cuda")
g3.edge("rust", "pluto")
g3.edge("rust", "uprof")
g3.edge("elixir", "phx")
g3.edge("js", "electron")
g3.edge("swift", "tensorflow")
g3.edge("go", "gogui")
g3.edge("gogui", "fayne")
g3.edge("go", "gogrpc")
g3.edge("go", "concur_chan")
g3.render()
os.rename("Digraph.gv.svg", "graph3.svg")