import graphviz
import os
g0=graphviz.Digraph(format="svg", comment="projects")
g0.node("concur_chan")
g0.node("gogrpc")
g0.node("fayne")
g0.node("gogui")
g0.node("tensorflow")
g0.node("electron")
g0.node("phx")
g0.node("uprof")
g0.node("cuda")
g0.node("finance")
g0.node("swift", color="blue", URL="https://github.com/plops/cl-swift-generator")
g0.node("matlab", color="blue", URL="https://github.com/plops/cl-m-generator")
g0.node("js", color="blue", URL="https://github.com/plops/cl-js-generator")
g0.node("go", color="blue", URL="https://github.com/plops/cl-golang-generator")
g0.node("elixir", color="blue", URL="https://github.com/plops/cl-elixir-generator")
g0.node("rust", color="blue", URL="https://github.com/plops/cl-rust-generator")
g0.node("kotlin", color="blue", URL="https://github.com/plops/cl-kotlin-generator")
g0.node("python", color="blue", URL="https://github.com/plops/cl-python-generator")
g0.node("cpp2", color="blue", URL="https://github.com/plops/cl-cpp-generator2")
g0.node("sar")
g0.node("pluto")
g0.node("android")
g0.node("sdr")
g0.node("sexpr")
g0.node("main")
g0.edge("main", "sexpr")
g0.edge("main", "sdr")
g0.edge("main", "android")
g0.edge("sdr", "pluto")
g0.edge("sdr", "sar")
g0.edge("sexpr", "cpp2")
g0.edge("sexpr", "python")
g0.edge("sexpr", "kotlin")
g0.edge("sexpr", "rust")
g0.edge("sexpr", "elixir")
g0.edge("sexpr", "go")
g0.edge("sexpr", "js")
g0.edge("sexpr", "matlab")
g0.edge("sexpr", "swift")
g0.edge("python", "finance")
g0.edge("rust", "cuda")
g0.edge("rust", "pluto")
g0.edge("rust", "uprof")
g0.edge("elixir", "phx")
g0.edge("js", "electron")
g0.edge("swift", "tensorflow")
g0.edge("go", "gogui")
g0.edge("gogui", "fayne")
g0.edge("go", "gogrpc")
g0.edge("go", "concur_chan")
g0.render()
os.rename("Digraph.gv.svg", "graph0.svg")
g1=graphviz.Digraph(format="svg", comment="projects")
g1.node("termimg")
g1.node("python_in_cpp")
g1.node("pybind11")
g1.node("asio")
g1.node("wx")
g1.node("imgui")
g1.node("fltk")
g1.node("qt")
g1.node("gtk")
g1.node("gui")
g1.node("sar")
g1.node("stm32")
g1.node("psoc")
g1.node("pluto")
g1.node("embed")
g1.node("tbb")
g1.node("lua_in_cpp")
g1.node("script")
g1.node("vulkan")
g1.node("cuda")
g1.node("wasm")
g1.node("optix")
g1.node("cpp2")
g1.edge("cpp2", "optix")
g1.edge("cpp2", "wasm")
g1.edge("cpp2", "cuda")
g1.edge("cpp2", "vulkan")
g1.edge("cpp2", "script")
g1.edge("script", "lua_in_cpp")
g1.edge("cpp2", "tbb")
g1.edge("cpp2", "embed")
g1.edge("embed", "pluto")
g1.edge("embed", "psoc")
g1.edge("embed", "stm32")
g1.edge("cpp2", "sar")
g1.edge("cpp2", "gui")
g1.edge("gui", "gtk")
g1.edge("gui", "qt")
g1.edge("gui", "fltk")
g1.edge("gui", "imgui")
g1.edge("gui", "wx")
g1.edge("cpp2", "asio")
g1.edge("cpp2", "script")
g1.edge("script", "pybind11")
g1.edge("pybind11", "python_in_cpp")
g1.edge("cpp2", "termimg")
g1.render()
os.rename("Digraph.gv.svg", "graph1.svg")
g2=graphviz.Digraph(format="svg", comment="projects")
g2.node("dask")
g2.node("cupy")
g2.node("pycuda")
g2.node("numba")
g2.node("pytorch")
g2.node("nlp")
g2.node("fastai2")
g2.node("fastai")
g2.node("megatron")
g2.node("waveguide")
g2.node("webengine")
g2.node("trellis")
g2.node("visdom")
g2.node("tkinter")
g2.node("glumpy")
g2.node("webkit")
g2.node("pyqt")
g2.node("gtk3")
g2.node("pywx")
g2.node("pygui")
g2.node("selenium")
g2.node("helium")
g2.node("autoweb")
g2.node("pyvulkan")
g2.node("ai")
g2.node("python")
g2.edge("python", "ai")
g2.edge("python", "pyvulkan")
g2.edge("python", "autoweb")
g2.edge("autoweb", "helium")
g2.edge("autoweb", "selenium")
g2.edge("python", "pygui")
g2.edge("pygui", "pywx")
g2.edge("pygui", "gtk3")
g2.edge("pygui", "pyqt")
g2.edge("pyqt", "webkit")
g2.edge("pygui", "glumpy")
g2.edge("pygui", "tkinter")
g2.edge("pygui", "visdom")
g2.edge("pyqt", "trellis")
g2.edge("pyqt", "webengine")
g2.edge("python", "waveguide")
g2.edge("ai", "megatron")
g2.edge("ai", "fastai")
g2.edge("ai", "fastai2")
g2.edge("fastai2", "nlp")
g2.edge("ai", "pytorch")
g2.edge("python", "numba")
g2.edge("python", "pycuda")
g2.edge("python", "cupy")
g2.edge("python", "dask")
g2.render()
os.rename("Digraph.gv.svg", "graph2.svg")
g3=graphviz.Digraph(format="svg", comment="projects")
g3.node("encrypt")
g3.node("compress")
g3.node("key_secure")
g3.node("gps")
g3.node("grpc")
g3.node("renderscript")
g3.node("camera")
g3.node("sensors")
g3.node("kot_opengles")
g3.node("kotlin")
g3.edge("kotlin", "kot_opengles")
g3.edge("kotlin", "sensors")
g3.edge("kotlin", "camera")
g3.edge("kotlin", "renderscript")
g3.edge("kotlin", "grpc")
g3.edge("kotlin", "gps")
g3.edge("kotlin", "key_secure")
g3.edge("kotlin", "compress")
g3.edge("kotlin", "encrypt")
g3.render()
os.rename("Digraph.gv.svg", "graph3.svg")